name: Deploy to Debian Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH with Passphrase
      run: |
        eval $(ssh-agent -s)  # Start the SSH agent
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - <<< "${{ secrets.SSH_PASSPHRASE }}"  # Add the SSH private key with the passphrase
        mkdir -p ~/.ssh  # Ensure the .ssh directory exists
        echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config  # Disable strict host key checking
      shell: bash

    - name: Copy files to server
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./Assets/Scripts/Server/ seraphis@67.205.148.170:/srv/cityrunnerserver/
