name: Deploy to Debian Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH with Passphrase
      run: |
        echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-keygen -P "${{ secrets.SSH_PASSPHRASE }}" -y
        eval $(ssh-agent -s)
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
      shell: bash

    - name: Copy files to server
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./Assets/Scripts/Server/ seraphis@67.205.148.170:/srv/cityrunnerserver/
